### ISSUE TITLE
Error Sending message on Real Device

### ISSUE THREAD

**Issue by chirag-ji** [shounakmulay/Telephony#149]
While sending an sms from a real device having android 11 with having permission: SEND_SMS,

call to function 
   ```
await telephony.sendSms(
      to: mobileNum,
      message: message,
      statusListener: onSendStatus,
    );
```

throwing an exception 

```
E/flutter (22839): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(failed_to_fetch_sms, Flutter Telephony: Error getting SmsManager, null, null)
E/flutter (22839): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (22839): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (22839): <asynchronous suspension>
E/flutter (22839): #2      Telephony.sendSms (package:telephony/telephony.dart:321:5)
E/flutter (22839): <asynchronous suspension>
```

**Comment by AchizuePriscilla** [comment]
Also having this issue

**Comment by crpo10** [comment]
also Having this issue, any news about it?

**Comment by mosi5505** [comment]
me too... i cant send sms...
Unhandled Exception: PlatformException(failed_to_fetch_sms, Flutter Telephony: Error getting SmsManager, null, null)

**Comment by Alashiq** [comment]
did you find any solution ?

**Comment by Alashiq** [comment]
> me too... i cant send sms... Unhandled Exception: PlatformException(failed_to_fetch_sms, Flutter Telephony: Error getting SmsManager, null, null)


did you find any solution ?

**Comment by AchizuePriscilla** [comment]
https://github.com/shounakmulay/Telephony/pull/153

The fix in this PR solved it for me

**Comment by imusman-khan** [comment]
Facing this issue too. Can anyone have the solution for this?

**Comment by appu-sm** [comment]
facing same issue, i'm wondered this issue is open for 1 year

**Comment by kudah99** [comment]
Facing this issue too...

**Comment by suhardik** [comment]
#153 

hope this help

**Comment by suhardik** [comment]
for everyone who facing this issue and still have no idea how to fix this... you can temporarily use package from my repository by changing telephony package inside pubspec.yaml

```
  telephony:
    git:
      url: https://github.com/suhardik/s_telephony.git
      ref: develop
```

![package example](https://user-images.githubusercontent.com/92511142/184279592-78c7fc7c-bd40-4888-9610-e9bd64a399f0.png)

**Comment by musfiqshanta** [comment]
e: /Users/shanta/FlutterSetUp/flutter/.pub-cache/git/s_telephony-78a83137120ce23b252454825272624ff37a8e1b/android/src/main/kotlin/com/shounakmulay/telephony/sms/SmsController.kt: (27, 7): Redeclaration: SmsController
e: /Users/shanta/FlutterSetUp/flutter/.pub-cache/hosted/pub.dartlang.org/telephony-0.2.0/android/src/main/kotlin/com/shounakmulay/telephony/sms/SmsController.kt: (27, 7): Redeclaration: SmsController

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':telephony:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by suhardik** [comment]
> e: /Users/shanta/FlutterSetUp/flutter/.pub-cache/git/s_telephony-78a83137120ce23b252454825272624ff37a8e1b/android/src/main/kotlin/com/shounakmulay/telephony/sms/SmsController.kt: (27, 7): Redeclaration: SmsController e: /Users/shanta/FlutterSetUp/flutter/.pub-cache/hosted/pub.dartlang.org/telephony-0.2.0/android/src/main/kotlin/com/shounakmulay/telephony/sms/SmsController.kt: (27, 7): Redeclaration: SmsController
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':telephony:compileDebugKotlin'.
> 
> > Compilation error. See log for more details
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14s Exception: Gradle task assembleDebug failed with exit code 1

i think its different problem. you can try to run "flutter pub clean" and then run "flutter pub get", and finally, run "flutter run"

**Comment by Smueez** [comment]
i have changed pubspec.yaml as you said. but yet i am facing the same issue.
i have ran flutter clean, flutter pub get
but yet the problem has not been resolved

**Comment by virtualars** [comment]
also problem myself, it doesn't work on old devices

**Comment by suhardik** [comment]
> also problem myself, it doesn't work on old devices

yes i guess. minSdkVersion of this library is 23. so it means that this library only works on device with OS Android 6.0 and later

**Comment by virtualars** [comment]
> > also problem myself, it doesn't work on old devices
> 
> yes i guess. minSdkVersion of this library is 23. so it means that this library only works on device with OS Android 6.0 and later

My sdk is 26 :(

**Comment by Endrikarab** [comment]
Hello! Is there someone who solved this problem?Thanks

**Comment by virtualars** [comment]
I changed plugin, I'm using this:
https://pub.dev/packages/background_sms

**Comment by brianXcode** [comment]
This problem still persist!

**Comment by suhardik** [comment]
almost 1 year but still not getting merged. for anyone who still get this error, you can try this solution:
https://github.com/shounakmulay/Telephony/issues/149#issuecomment-1212695720

hope this help :)

**Comment by djabiridrissou** [comment]
> almost 1 year but still not getting merged. for anyone who still get this error, you can try this solution: [#149 (comment)](https://github.com/shounakmulay/Telephony/issues/149#issuecomment-1212695720)
> 
> hope this help :)

This help boss, thank you
